### ISSUE TITLE
Encountered an error during the complete event phase: Java NoSuchMethodError

### ISSUE THREAD

**Issue by AnonymousHacker1279** [mezz/TextureDump#17]
I have placed the mod into the ``mods`` folder of my development environment. Attempting to launch the game results in a ``java.lang.NoSuchMethodError: net.minecraft.client.Minecraft.func_71410_x()Lnet/minecraft/client/Minecraft``. Apparently the issue is on line 50: where the Minecraft instance is obtained. 

As such I believe this could possibly be an issue with new Forge mappings: at the moment they are ``20210309-1.16.5`` for me. My Forge is currently at 1.16.5-36.0.48. 

I have attached the crash report below.

[crash-2021-03-10_21.29.53-fml.txt](https://github.com/mezz/TextureDump/files/6120068/crash-2021-03-10_21.29.53-fml.txt)

**Comment by mezz** [comment]
Thanks for the report!
I have created a version updated to be built against the latest Forge. 
I think it should work, please let me know if you run into any issues with it.
