### ISSUE TITLE
Rendering Overlay crash on launch

### ISSUE THREAD

**Issue by SwankyStella** [mezz/TextureDump#20]
Hello,
Upon launching my custom modpack, which opens just fine without TextureDump, the game now closes with a "Rendering Overlay" error. The game crashes after loading completely (even going as far as having the ding mod... ding), but before the main menu can load. Tried my best to figure out if it was a specific mod conflict but I can't seem to find whether its texture dump or another.

Crashlog is here: https://pastebin.com/9jHCpc6v

**Comment by mezz** [comment]
Thanks for the report!
I have released a new version that fixes this: `texturedump_1.16.5-1.15`.
It should show up here soon: https://www.curseforge.com/minecraft/mc-mods/texture-dump/files/all
