### ISSUE TITLE
[1.16.5] Path slashes is missing inside html files

### ISSUE THREAD

**Issue by nikita488** [mezz/TextureDump#21]
The paths to all resources are missing slashes:
![image](https://user-images.githubusercontent.com/6237881/136918435-b86c026f-b364-4df9-b7dc-bec664a53f7f.png)
Leading to this result:
![image](https://user-images.githubusercontent.com/6237881/136918483-8326d8de-64a5-4f37-afe5-d47cc2bd9cee.png)
Adding slashes by hand fixes everything.

**Comment by mezz** [comment]
Thanks for the report!
It looks like I broke this on Windows, it's trying to use the Windows separator character `\` which doesn't work in HTML.

**Comment by mezz** [comment]
I have uploaded fixed versions of the mod for 1.16 and 1.17. 
I am not able to test on Windows but it should work, please let me know if you have any more issues!

**Comment by nikita488** [comment]
Works perfectly! Thank you :)
![image](https://user-images.githubusercontent.com/6237881/146748375-3ae3c711-a6d2-4a9a-ab83-264fb8afc48e.png)

**Comment by mezz** [comment]
Great! Thank you for confirming
