### ISSUE TITLE
Statistics in texture domain sizes

### ISSUE THREAD

**Issue by Drullkus** [mezz/TextureDump#3]
We should have percentages in how much space each texture domain takes up, so there is a better estimate on which mods take up the most amount of space. Currently looking at [this](http://i.imgur.com/JHiAbwj.png) is like looking at a jar of colored marbles and guessing which color has the most marbles in a jar.

**Comment by Drullkus** [comment]
Thanks! I'd like to have minecraft in the stat list too, though. It would be helpful as resourcepacks can change the data on the dumped sheet.

**Comment by mezz** [comment]
Minecraft is in the stat list

**Comment by Drullkus** [comment]
Whoops, I wasn't looking hard enough. x3
