### ISSUE TITLE
Long texture names overlap the texture atlas

### ISSUE THREAD

**Issue by mezz** [mezz/TextureDump#4]
There should be more space for the texture name so it does not overlap.
Maybe the texture atlas image could be drawn lower.

**Comment by Drullkus** [comment]
I thought they wrapped.
<img width="405" alt="screen shot 2016-10-24 at 4 30 05 pm" src="https://cloud.githubusercontent.com/assets/5010174/19667686/309fe1b0-9a07-11e6-90ae-0854c55d6395.png">

**Comment by AtomicBlom** [comment]
Eh, it only wraps when there's a hyphen or a dot, :(

I'm going to move it to the titlebar which will fix this.

**Comment by Drullkus** [comment]
Whoops! I see what you're talking about now. Why not a little bit of css to fix that? You can just apply it in the header.
