### ISSUE TITLE
Html uses wrong file when looking at mips

### ISSUE THREAD

**Issue by Drullkus** [mezz/TextureDump#5]
[Download relevant files here](https://dl.dropboxusercontent.com/s/l57cpe18vm8alt9/Archive.zip)

The HTML uses the mip 0 file on all mip previews, instead of corresponding mip sizes.

**Comment by AtomicBlom** [comment]
o_O; I swear I've fixed that 3 times now.

**Comment by Drullkus** [comment]
Not only that, but it's also slicing it wrong. Probably symptom of wrong file. This is from Mip 3.

<img width="516" alt="screen shot 2016-10-24 at 4 49 19 pm" src="https://cloud.githubusercontent.com/assets/5010174/19668060/d5a6a14c-9a09-11e6-8d9b-de250aa38c62.png">

**Comment by AtomicBlom** [comment]
That would happen when the json data doesn't match the png

**Comment by mezz** [comment]
I think I fixed this in version 1.1, have you tried updating?
https://github.com/mezz/TextureDump/commit/3cc510976a27f105981f835d10aaf8f0e363a819

**Comment by mezz** [comment]
Yeah this is definitely fixed.

**Comment by Drullkus** [comment]
Can confirm fix
