### ISSUE TITLE
HTML Page looks ugly

### ISSUE THREAD

**Issue by AtomicBlom** [mezz/TextureDump#6]
The page looks truely atrocious.

I'm investigating reading a background tile out of the image map and using that as the background, but it also needs some CSS magic to improve the layout and make it more user friendly, especially if I add per-mod statistics

**Comment by AtomicBlom** [comment]
This is a bit of a preview of what I've been working on. I still need to improve the readability, and I don't think the transparency shows well on the left-hand panel.

The fun thing about this is that it will use the textures from the sprite sheet if it can find them.

![image](https://cloud.githubusercontent.com/assets/3894692/19673980/3f179c7c-9acc-11e6-832b-7f54c7d7f4bf.png)

**Comment by mezz** [comment]
Clever :D
